/* Generated by Alien constants */

#include <stdio.h>

#include <cdk.h>
#define LUA_FILE "../Lua/CDK/Constants.lua"
int main() {
  FILE *f = fopen(LUA_FILE, "w+");
  fprintf(f, "-- Generated by Alien constants\n\n");
  fprintf(f, "local M = {\n");
  fprintf(f, "    %s = %i,\n", "vNULL", vNULL);
  fprintf(f, "    %s = %i,\n", "vALPHALIST", vALPHALIST);
  fprintf(f, "    %s = %i,\n", "vBUTTON", vBUTTON);
  fprintf(f, "    %s = %i,\n", "vBUTTONBOX", vBUTTONBOX);
  fprintf(f, "    %s = %i,\n", "vCALENDAR", vCALENDAR);
  fprintf(f, "    %s = %i,\n", "vDIALOG", vDIALOG);
  fprintf(f, "    %s = %i,\n", "vDSCALE", vDSCALE);
  fprintf(f, "    %s = %i,\n", "vENTRY", vENTRY);
  fprintf(f, "    %s = %i,\n", "vFSCALE", vFSCALE);
  fprintf(f, "    %s = %i,\n", "vFSELECT", vFSELECT);
  fprintf(f, "    %s = %i,\n", "vFSLIDER", vFSLIDER);
  fprintf(f, "    %s = %i,\n", "vGRAPH", vGRAPH);
  fprintf(f, "    %s = %i,\n", "vHISTOGRAM", vHISTOGRAM);
  fprintf(f, "    %s = %i,\n", "vITEMLIST", vITEMLIST);
  fprintf(f, "    %s = %i,\n", "vLABEL", vLABEL);
  fprintf(f, "    %s = %i,\n", "vMARQUEE", vMARQUEE);
  fprintf(f, "    %s = %i,\n", "vMATRIX", vMATRIX);
  fprintf(f, "    %s = %i,\n", "vMENTRY", vMENTRY);
  fprintf(f, "    %s = %i,\n", "vMENU", vMENU);
  fprintf(f, "    %s = %i,\n", "vRADIO", vRADIO);
  fprintf(f, "    %s = %i,\n", "vSCALE", vSCALE);
  fprintf(f, "    %s = %i,\n", "vSCROLL", vSCROLL);
  fprintf(f, "    %s = %i,\n", "vSELECTION", vSELECTION);
  fprintf(f, "    %s = %i,\n", "vSLIDER", vSLIDER);
  fprintf(f, "    %s = %i,\n", "vSWINDOW", vSWINDOW);
  fprintf(f, "    %s = %i,\n", "vTEMPLATE", vTEMPLATE);
  fprintf(f, "    %s = %i,\n", "vTRAVERSE", vTRAVERSE);
  fprintf(f, "    %s = %i,\n", "vUSCALE", vUSCALE);
  fprintf(f, "    %s = %i,\n", "vUSLIDER", vUSLIDER);
  fprintf(f, "    %s = %i,\n", "vVIEWER", vVIEWER);
  fprintf(f, "    %s = %i,\n", "vINVALID", vINVALID);
  fprintf(f, "    %s = %i,\n", "vCHAR", vCHAR);
  fprintf(f, "    %s = %i,\n", "vHCHAR", vHCHAR);
  fprintf(f, "    %s = %i,\n", "vINT", vINT);
  fprintf(f, "    %s = %i,\n", "vHINT", vHINT);
  fprintf(f, "    %s = %i,\n", "vMIXED", vMIXED);
  fprintf(f, "    %s = %i,\n", "vHMIXED", vHMIXED);
  fprintf(f, "    %s = %i,\n", "vUCHAR", vUCHAR);
  fprintf(f, "    %s = %i,\n", "vLCHAR", vLCHAR);
  fprintf(f, "    %s = %i,\n", "vUHCHAR", vUHCHAR);
  fprintf(f, "    %s = %i,\n", "vLHCHAR", vLHCHAR);
  fprintf(f, "    %s = %i,\n", "vUMIXED", vUMIXED);
  fprintf(f, "    %s = %i,\n", "vLMIXED", vLMIXED);
  fprintf(f, "    %s = %i,\n", "vUHMIXED", vUHMIXED);
  fprintf(f, "    %s = %i,\n", "vLHMIXED", vLHMIXED);
  fprintf(f, "    %s = %i,\n", "vVIEWONLY", vVIEWONLY);
  fprintf(f, "    %s = %i,\n", "vNONE ", vNONE );
  fprintf(f, "    %s = %i,\n", "vPERCENT", vPERCENT);
  fprintf(f, "    %s = %i,\n", "vFRACTION", vFRACTION);
  fprintf(f, "    %s = %i,\n", "vREAL", vREAL);
  fprintf(f, "    %s = %i,\n", "vPLOT", vPLOT);
  fprintf(f, "    %s = %i,\n", "vLINE", vLINE);
  fprintf(f, "    %s = %i,\n", "vFRONT", vFRONT);
  fprintf(f, "    %s = %i,\n", "vBACK", vBACK);
  fprintf(f, "    %s = %i,\n", "vBOTH", vBOTH);
  fprintf(f, "    %s = %i,\n", "vEARLY_EXIT", vEARLY_EXIT);
  fprintf(f, "    %s = %i,\n", "vESCAPE_HIT", vESCAPE_HIT);
  fprintf(f, "    %s = %i,\n", "vNORMAL", vNORMAL);
  fprintf(f, "    %s = %i,\n", "vNEVER_ACTIVATED", vNEVER_ACTIVATED);
  fprintf(f, "    %s = %i,\n", "vERROR", vERROR);
  fprintf(f, "    %s = %i,\n", "LEFT ", LEFT );
  fprintf(f, "    %s = %i,\n", "RIGHT ", RIGHT );
  fprintf(f, "    %s = %i,\n", "CENTER", CENTER);
  fprintf(f, "    %s = %i,\n", "TOP", TOP);
  fprintf(f, "    %s = %i,\n", "BOTTOM ", BOTTOM );
  fprintf(f, "    %s = %i,\n", "HORIZONTAL", HORIZONTAL);
  fprintf(f, "    %s = %i,\n", "VERTICAL", VERTICAL);
  fprintf(f, "    %s = %i,\n", "FULL", FULL);
  fprintf(f, "    %s = %i,\n", "NONE", NONE);
  fprintf(f, "    %s = %i,\n", "ROW", ROW);
  fprintf(f, "    %s = %i,\n", "COL", COL);
  fprintf(f, "    %s = %i,\n", "MAX_BINDINGS", MAX_BINDINGS);
  fprintf(f, "    %s = %i,\n", "MAX_ITEMS", MAX_ITEMS);
  fprintf(f, "    %s = %i,\n", "MAX_BUTTONS", MAX_BUTTONS);
  fprintf(f, "\n}\n\n");
  fprintf(f, "return {\n\tforPackage = function (pkg)\n\t\tfor k, v in pairs(M) do\n\t\t\tpkg[k] = M[k]\n\t\tend\n\t\treturn pkg\n\tend\n}");
  fclose(f);
}
